# Generated by Django 4.2.7 on 2025-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='package_covers/')),
                ('tour_highlights', models.JSONField()),
                ('tour_details', models.JSONField()),
            ],
        ),
    ]
