# Generated by Django 5.2.7 on 2025-10-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in days'),
        ),
        migrations.AddField(
            model_name='package',
            name='group_size',
            field=models.PositiveIntegerField(default=10, help_text='Maximum group size'),
        ),
        migrations.AlterField(
            model_name='package',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Image URL or path', max_length=500, null=True),
        ),
    ]
