# Generated by Django 4.2.7 on 2025-10-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('traveler_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='toures.package')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='system.traveler')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='toures.package')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='system.ticket')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='system.traveler')),
            ],
        ),
    ]
