# Generated by Django 4.2.7 on 2025-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='esewa_raw_response',
            field=models.TextField(blank=True, help_text='Full eSewa API response for audit', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='esewa_signature',
            field=models.TextField(blank=True, help_text='eSewa payment signature', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='esewa_status',
            field=models.CharField(blank=True, help_text='eSewa transaction status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='esewa_transaction_code',
            field=models.CharField(blank=True, help_text='eSewa transaction code/reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='esewa_transaction_uuid',
            field=models.CharField(blank=True, help_text='eSewa transaction UUID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='esewa', help_text='Payment method used', max_length=50),
        ),
    ]
